### ISSUE TITLE
Add KhronosGroup/Vulkan-Tools

### ISSUE THREAD

**Issue by dneto0** [google/vkb#72] opened 2020-01-16 17:19 UTC
https://github.com/KhronosGroup/Vulkan-Tools has a few things:
 
  Mock ICD
  Vkcube and Vkcube++ Demo
  VulkanInfo
  Windows Runtime Installer

**Comment by dj2** [comment] 2020-01-16 17:52
Duplicate of #7

**Closed as completed by dj2** 2020-01-16 17:52 UTC
Labels: duplicate
